TASK: Change to Neos 3.0 requirements
neos/neos-base-distribution pull request #20
Opened 2016-12-25 14:20 UTC by daniellienert

2016-12-27 10:53 UTC, Sebobo requested changes

2016-12-27 10:53 UTC, Sebobo commented on composer.json
> +        "neos/redirecthandler": "@dev",
@daniellienert I think these should all be `4.0.x-dev`. Didn't get the right version with `@dev`.

2016-12-30 07:52 UTC, daniellienert commented on composer.json
> +        "neos/redirecthandler": "@dev",
@Sebobo: Please try again. The neos/redirecthandler currently needs the @dev due to the version constraints of the redirecthandler packages. The others are (branched and) fixed.

2016-12-30 13:03 UTC, Sebobo approved these changes

2017-01-03 11:04 UTC, merged